# Generated by Django 5.1.7 on 2025-03-15 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=512, null=True)),
                ('morada', models.CharField(blank=True, max_length=512, null=True)),
                ('dt_criacao', models.DateTimeField(default=datetime.datetime(2025, 3, 15, 17, 3, 10, 283977))),
                ('email', models.CharField(blank=True, max_length=512, null=True)),
                ('telem', models.IntegerField(blank=True, max_length=15, null=True)),
                ('telef', models.IntegerField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
    ]
